language: java
dist: trusty
sudo: false

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - chromium-chromedriver
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # copy Maven settings
  - cp .travis.settings.xml "${HOME}/.m2/settings.xml"
  
  # include GeckoDriver in PATH
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version
  - export MOZ_HEADLESS=1
  
  # connects firefox to the D-BUS daemon
  - export $(dbus-launch)
  - export NSS_USE_SHARED_DB=ENABLED

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  # decrypt ReTest secret key
  - openssl aes-256-cbc -K $encrypted_5faff216b858_key -iv $encrypted_5faff216b858_iv
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  # import decrypted ReTest secret key
  - gpg --fast-import retest-gmbh-gpg.asc
  # package JARs for release providers
  - mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/recheck-web-*.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master

after_deploy:
  - mvn deploy -DskipTests
