language: java
sudo: false

addons:
  sonarcloud:
    organization: "retest"
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - ${HOME}/.m2/
    - ${HOME}/.sonar/cache/

before_install:
- openssl aes-256-cbc -K $encrypted_5faff216b858_key -iv $encrypted_5faff216b858_iv
    -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
- gpg --fast-import retest-gmbh-gpg.asc

install: true

before_script:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

before_deploy: mvn package -DskipTests

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/recheck-web-*.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master
