language: java
dist: trusty
sudo: false

env:
  - MVN="mvn --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml"

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - chromium-chromedriver
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

before_script:
  # set up ChromeDriver
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # set up GeckoDriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH="${PATH}:${PWD}/geckodriver"
  - geckodriver --version
  - export MOZ_HEADLESS=1
  # connect Firefox to the D-BUS daemon
  - export $(dbus-launch)
  - export NSS_USE_SHARED_DB=ENABLED

script:
  - ${MVN} clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  # decrypt ReTest secret key
  - openssl aes-256-cbc -K ${encrypted_5faff216b858_key} -iv ${encrypted_5faff216b858_iv}
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  # import decrypted ReTest secret key
  - gpg --fast-import --import-options merge-only retest-gmbh-gpg.asc
  # package and sign artifacts
  - ${MVN} verify -DskipTests -P sign

deploy:
  # deploy artifacts to Maven Central
  - provider: script
    script: ${MVN} deploy -DskipTests
    on:
      tags: true
