language: java
dist: trusty

jdk: openjdk8

git:
  depth: false

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - chromium-chromedriver
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

before_script: ci/before.sh

script: ci/script.sh

before_deploy: ci/before_deploy.sh

deploy:
  - provider: script
    script: ci/deploy.sh
    on:
      tags: true
  - provider: releases
    api_key: "${GH_TOKEN}"
    file_glob: true
    file: "target/recheck-web-*-jar-with-dependencies.jar"
    skip_cleanup: true
    draft: true
    on:
      tags: true
